export const OPEN_AUTH = "OPEN_AUTH";
export const ADD_MOVIES = "ADD_MOVIES";
export const ADD_ACTIVE_MOVIE = "ADD_ACTIVE_MOVIE";
export const ADD_THEATRE_LIST = "ADD_THEATRE_LIST";
export const BOOK_TICKET_MESSAGE = "BOOK_TICKET_MESSAGE"
